name: sos_app
description: "A new Flutter project."
# Prevents the package from being accidentally published to pub.dev using
# `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icônes style iOS
  cupertino_icons: ^1.0.2

  # AJOUT : Package pour lancer des appels, ouvrir des liens, etc.
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints officiels pour encourager les bonnes pratiques de code
  flutter_lints: ^3.0.0

# Configuration spécifique à Flutter
flutter:
  
  # Active les icônes Material Design
  uses-material-design: true

  # Pour ajouter des assets (images) plus tard, vous décommenterez ces lignes :
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg