name: sos_app
description: "Application d'urgence SOS pour alerter rapidement en cas de besoin avec localisation et alarme."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.3.0
  
  # AJOUT : Packages pour la localisation et le son
  geolocator: ^10.1.0
  audioplayers: ^5.2.1
  flutter_map: ^6.2.1
  latlong2: ^0.9.1
  shared_preferences: ^2.2.2
  flutter_contacts: ^1.1.9+2
  path_provider: ^2.1.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  
  # AJOUT : Assets pour le fichier audio
  assets:
    - assets/alarm_sound.mp3